/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caccia;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 *
 * @author ruben
 */
public class FormSalvataggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSalvataggio.class.getName());

    gestoreForm g;
    JPanel panel;
    boolean salvataggio;
    /**
     * Creates new form FormSalvataggio
     */
    public FormSalvataggio(int w,int h,gestoreForm g,boolean salvataggio) {
        initComponents();
        
        this.setSize(w,h);
        this.g=g;
        this.salvataggio=salvataggio;
        
        panel = new JPanel(new GridBagLayout()) {
            Image sfondo = new ImageIcon("immagini/sfondoMenu.jpg").getImage();
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(sfondo, 0, 0, getWidth(), getHeight(), this);
            }
        };

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 50, 10, 50); 
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;

        JLabel lblTitolo = new JLabel("SELEZIONA SALVATAGGIO", JLabel.CENTER);
        lblTitolo.setFont(new Font("Arial", Font.BOLD, 22));
        lblTitolo.setForeground(Color.WHITE);
        gbc.gridy = 0;
        gbc.insets = new Insets(30, 50, 30, 50);
        panel.add(lblTitolo, gbc);

        gbc.insets = new Insets(10, 50, 10, 50);

        gbc.gridy = 1;
        panel.add(creaRigaSalvataggio(1, "save1.ser"), gbc);

        gbc.gridy = 2;
        panel.add(creaRigaSalvataggio(2, "save2.ser"), gbc);

        gbc.gridy = 3;
        panel.add(creaRigaSalvataggio(3, "save3.ser"), gbc);

        this.setLayout(new BorderLayout());
        this.add(panel);
    }

    private JPanel creaRigaSalvataggio(int id, String nomeFile) {
        JPanel riga = new JPanel(new BorderLayout(20, 0)) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(0, 0, 0, 160));
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 50, 50);
                g2.setColor(Color.WHITE);
                g2.setStroke(new BasicStroke(2));
                g2.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 50, 50);
                g2.dispose();
            }
        };
        riga.setOpaque(false);
        riga.setBorder(BorderFactory.createEmptyBorder(15, 30, 15, 30));

        JLabel lblInfo = new JLabel("SLOT " + id +" "+ nomeFile);
        lblInfo.setForeground(Color.WHITE);
        lblInfo.setFont(new Font("Arial", Font.PLAIN, 16));

        JButton btnLoad = new JButton("LOAD");

        btnLoad.addActionListener(e -> {
            if(salvataggio==true){
                try {
                    g.salvaDati(nomeFile);
                    g.aproGioco(this.getWidth(), this.getHeight());

                } catch (ClassNotFoundException ex) {
                }
            }
            else{
                try {
                    g.caricaDati(nomeFile);
                    g.creoGioco(this.getWidth(), this.getHeight());
                } catch (ClassNotFoundException ex) {
                }
            }
            
            this.dispose();
        });

        riga.add(lblInfo, BorderLayout.CENTER);
        riga.add(btnLoad, BorderLayout.EAST);

        return riga;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
