/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caccia;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ruben
 */
public class FormInventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormInventario.class.getName());
    
    gestoreForm g;
    /**
     * Creates new form FormInventario
     */
    public FormInventario(gestoreForm ge,int w,int h) {
        initComponents();
        
        this.setSize(w, h);
        
        this.g=ge;
        
        JPanel panel = new JPanel() {
            Image immagineZaino=new ImageIcon("immagini/zainoAperto.png").getImage();
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(immagineZaino, 0, 0, getWidth(), getHeight(), this);
            }
        };
        panel.setLayout(new GridLayout(2,1,10,10));
        
        //panelSopra
        JPanel panelSopra=new JPanel();
        panelSopra.setLayout(new GridBagLayout());
        
        GridBagConstraints gbc=new GridBagConstraints();
        GridBagConstraints gbcSopra=new GridBagConstraints();
        panelSopra.setOpaque(false);
        
        //pezzo vuotoSopra
        gbc.gridx=0;
        gbc.weightx=0.34;
        gbc.fill = GridBagConstraints.BOTH;
        
        JPanel vuotoSopra=new JPanel();
        vuotoSopra.setOpaque(false);
        
        gbcSopra.gridy=0;
        gbcSopra.gridheight = GridBagConstraints.REMAINDER;
        
        gbcSopra.gridx=0;
        gbcSopra.weightx=0.33;
       
        panelSopra.add(vuotoSopra,gbcSopra);
        
        gbcSopra.gridx=1;
        gbcSopra.weightx=0.67;
        
        JPanel bottoni=new JPanel();
        bottoni.setLayout(new GridBagLayout());
        GridBagConstraints gbcBottoni=new GridBagConstraints();
        
        gbcBottoni.gridx=1;
        gbcBottoni.weightx=1;
        gbcBottoni.gridheight = GridBagConstraints.REMAINDER;
        
        gbcBottoni.gridy=0;
        gbcBottoni.weighty=0.16;
        bottoni.add(new JPanel(),gbcBottoni);
        
        gbcBottoni.gridy=1;
        gbcBottoni.weighty=0.18;
        JPanel oggetto1=new JPanel();
        oggetto1.setBackground(Color.GREEN);
        bottoni.add(oggetto1,gbcBottoni);
        
        gbcBottoni.gridy=2;
        gbcBottoni.weighty=0.05;
        bottoni.add(new JPanel(),gbcBottoni);
        
        gbcBottoni.gridy=3;
        gbcBottoni.weighty=0.18;
        JPanel oggetto2=new JPanel();
        oggetto2.setBackground(Color.GREEN);
        bottoni.add(oggetto2,gbcBottoni);
        
        gbcBottoni.gridy=4;
        gbcBottoni.weighty=0.05;
        bottoni.add(new JPanel(),gbcBottoni);
        
        gbcBottoni.gridy=5;
        gbcBottoni.weighty=0.18;
        JPanel oggetto3=new JPanel();
        oggetto3.setBackground(Color.GREEN);
        bottoni.add(oggetto3,gbcBottoni);
        
        gbcBottoni.gridy=6;
        gbcBottoni.weighty=0.2;
        bottoni.add(new JPanel(),gbcBottoni);
        
        panelSopra.add(bottoni,gbcSopra);
        
        panel.add(panelSopra);
        panel.add(new JPanel());
        
        this.setLayout(new BorderLayout());
        this.add(panel);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
