/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caccia;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ruben
 */
public class SceltaPersonaggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SceltaPersonaggio.class.getName());


    public SceltaPersonaggio() {
        initComponents();

        JButton[] cacciatori = new JButton[4];

        for (int i = 0; i < 4; i++) {
            Image immagine=new ImageIcon("immagini/g"+(i+1)+".png").getImage();
            
            JButton b=creoBottone(immagine,cacciatori);
            
            cacciatori[i] = b;
        }

        JPanel panel = new JPanel() {
            Image imgSfondo = new ImageIcon("immagini/sceltaPersonaggio.png").getImage();
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imgSfondo, 0, 0, getWidth(), getHeight(), this);
            }
        };
        
        panel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        
        //panel in alto
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1;
        gbc.weighty = 0.25;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel panelUpp = new JPanel();
        panelUpp.setOpaque(false);
        panel.add(panelUpp, gbc);

        //panel con bottoni
        JPanel panelPiccolo = new JPanel();
        panelPiccolo.setLayout(new GridLayout(1, 4, 20, 20));
        panelPiccolo.setOpaque(false);
        for (JButton b : cacciatori) {
            panelPiccolo.add(b);
        }
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1;
        gbc.weighty = 0.6;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.anchor = GridBagConstraints.CENTER;   
        panel.add(panelPiccolo, gbc);

        //panel in fondo
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1;
        gbc.weighty = 0.15;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        JPanel panelDown = new JPanel();
        panelDown.setLayout(new GridLayout(1, 3, 20, 20));
        panelDown.setOpaque(false);
        panelDown.add(new JLabel(""));
        panelDown.add(new JButton("Scegli cacciatore"));
        panelDown.add(new JLabel(""));
        panel.add(panelDown, gbc);
        
        
        this.setLayout(new BorderLayout());
        this.add(panel);
        
    }

    public JButton creoBottone(Image immagine,JButton[] cacciatori){
        JButton b = new JButton(){
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g); 
                    Graphics2D g2d = (Graphics2D) g.create();

                    g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);

                    g2d.drawImage(immagine, 0, 0, getWidth(), getHeight(), this);

                    g2d.dispose();//non devo farlo per forza ma logicamente è piu bello (tolgo il pennello che ho usato per dipingere)
                }
            };
        
        b.setBorderPainted(false);
        b.setContentAreaFilled(false);
        b.setFocusPainted(false);
        b.setOpaque(false);
        
        aggiungiListener(b,cacciatori);
        return b;
    }
    public void aggiungiListener(JButton b,JButton[] cacciatori){
        b.addActionListener(e -> {
                for (JButton btn : cacciatori) {
                    btn.setBorder(null);
                }
                b.setBorderPainted(true);
                b.setBorder(BorderFactory.createLineBorder(Color.YELLOW, 4));
            });  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SceltaPersonaggio().setVisible(true));
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
